// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: media.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusEnum int32

const (
	StatusEnum_ready  StatusEnum = 0
	StatusEnum_failed StatusEnum = 1
)

// Enum value maps for StatusEnum.
var (
	StatusEnum_name = map[int32]string{
		0: "ready",
		1: "failed",
	}
	StatusEnum_value = map[string]int32{
		"ready":  0,
		"failed": 1,
	}
)

func (x StatusEnum) Enum() *StatusEnum {
	p := new(StatusEnum)
	*p = x
	return p
}

func (x StatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_media_proto_enumTypes[0].Descriptor()
}

func (StatusEnum) Type() protoreflect.EnumType {
	return &file_media_proto_enumTypes[0]
}

func (x StatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusEnum.Descriptor instead.
func (StatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

type CreateUploadSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purpose       string                 `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadSessionRequest) Reset() {
	*x = CreateUploadSessionRequest{}
	mi := &file_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadSessionRequest) ProtoMessage() {}

func (x *CreateUploadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadSessionRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUploadSessionRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *CreateUploadSessionRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateUploadSessionRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type CreateUploadSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadSessionResponse) Reset() {
	*x = CreateUploadSessionResponse{}
	mi := &file_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadSessionResponse) ProtoMessage() {}

func (x *CreateUploadSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadSessionResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUploadSessionResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *CreateUploadSessionResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

type ConfirmUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadRequest) Reset() {
	*x = ConfirmUploadRequest{}
	mi := &file_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadRequest) ProtoMessage() {}

func (x *ConfirmUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUploadRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmUploadRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type ConfirmUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Status        StatusEnum             `protobuf:"varint,2,opt,name=status,proto3,enum=pb.StatusEnum" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadResponse) Reset() {
	*x = ConfirmUploadResponse{}
	mi := &file_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadResponse) ProtoMessage() {}

func (x *ConfirmUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadResponse.ProtoReflect.Descriptor instead.
func (*ConfirmUploadResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmUploadResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *ConfirmUploadResponse) GetStatus() StatusEnum {
	if x != nil {
		return x.Status
	}
	return StatusEnum_ready
}

type GetOneMediaByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneMediaByIdRequest) Reset() {
	*x = GetOneMediaByIdRequest{}
	mi := &file_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneMediaByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneMediaByIdRequest) ProtoMessage() {}

func (x *GetOneMediaByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneMediaByIdRequest.ProtoReflect.Descriptor instead.
func (*GetOneMediaByIdRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{4}
}

func (x *GetOneMediaByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OneMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneMediaResponse) Reset() {
	*x = OneMediaResponse{}
	mi := &file_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneMediaResponse) ProtoMessage() {}

func (x *OneMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneMediaResponse.ProtoReflect.Descriptor instead.
func (*OneMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{5}
}

func (x *OneMediaResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OneMediaURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneMediaURLResponse) Reset() {
	*x = OneMediaURLResponse{}
	mi := &file_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneMediaURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneMediaURLResponse) ProtoMessage() {}

func (x *OneMediaURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneMediaURLResponse.ProtoReflect.Descriptor instead.
func (*OneMediaURLResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{6}
}

func (x *OneMediaURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_media_proto protoreflect.FileDescriptor

const file_media_proto_rawDesc = "" +
	"\n" +
	"\vmedia.proto\x12\x02pb\x1a\x1bbuf/validate/validate.proto\"\x91\x01\n" +
	"\x1aCreateUploadSessionRequest\x12!\n" +
	"\apurpose\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\apurpose\x12*\n" +
	"\fcontent_type\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vcontentType\x12$\n" +
	"\tfile_name\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bfileName\"W\n" +
	"\x1bCreateUploadSessionResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\":\n" +
	"\x14ConfirmUploadRequest\x12\"\n" +
	"\bmedia_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\amediaId\"d\n" +
	"\x15ConfirmUploadResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0e.pb.StatusEnumB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06status\"(\n" +
	"\x16GetOneMediaByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10OneMediaResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x13OneMediaURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url*#\n" +
	"\n" +
	"StatusEnum\x12\t\n" +
	"\x05ready\x10\x00\x12\n" +
	"\n" +
	"\x06failed\x10\x01B.Z,github.com/daniel-bss/havlabs-proto/media/pbb\x06proto3"

var (
	file_media_proto_rawDescOnce sync.Once
	file_media_proto_rawDescData []byte
)

func file_media_proto_rawDescGZIP() []byte {
	file_media_proto_rawDescOnce.Do(func() {
		file_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)))
	})
	return file_media_proto_rawDescData
}

var file_media_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_media_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_media_proto_goTypes = []any{
	(StatusEnum)(0),                     // 0: pb.StatusEnum
	(*CreateUploadSessionRequest)(nil),  // 1: pb.CreateUploadSessionRequest
	(*CreateUploadSessionResponse)(nil), // 2: pb.CreateUploadSessionResponse
	(*ConfirmUploadRequest)(nil),        // 3: pb.ConfirmUploadRequest
	(*ConfirmUploadResponse)(nil),       // 4: pb.ConfirmUploadResponse
	(*GetOneMediaByIdRequest)(nil),      // 5: pb.GetOneMediaByIdRequest
	(*OneMediaResponse)(nil),            // 6: pb.OneMediaResponse
	(*OneMediaURLResponse)(nil),         // 7: pb.OneMediaURLResponse
}
var file_media_proto_depIdxs = []int32{
	0, // 0: pb.ConfirmUploadResponse.status:type_name -> pb.StatusEnum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_media_proto_init() }
func file_media_proto_init() {
	if File_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_proto_goTypes,
		DependencyIndexes: file_media_proto_depIdxs,
		EnumInfos:         file_media_proto_enumTypes,
		MessageInfos:      file_media_proto_msgTypes,
	}.Build()
	File_media_proto = out.File
	file_media_proto_goTypes = nil
	file_media_proto_depIdxs = nil
}
