// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: news.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOneNewsByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneNewsByIdRequest) Reset() {
	*x = GetOneNewsByIdRequest{}
	mi := &file_news_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneNewsByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneNewsByIdRequest) ProtoMessage() {}

func (x *GetOneNewsByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneNewsByIdRequest.ProtoReflect.Descriptor instead.
func (*GetOneNewsByIdRequest) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{0}
}

func (x *GetOneNewsByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateNewsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CreatorUsername string                 `protobuf:"bytes,1,opt,name=creator_username,json=creatorUsername,proto3" json:"creator_username,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateNewsRequest) Reset() {
	*x = CreateNewsRequest{}
	mi := &file_news_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewsRequest) ProtoMessage() {}

func (x *CreateNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewsRequest.ProtoReflect.Descriptor instead.
func (*CreateNewsRequest) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNewsRequest) GetCreatorUsername() string {
	if x != nil {
		return x.CreatorUsername
	}
	return ""
}

func (x *CreateNewsRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNewsRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateNewsByIdRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CreatorUsername string                 `protobuf:"bytes,1,opt,name=creator_username,json=creatorUsername,proto3" json:"creator_username,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateNewsByIdRequest) Reset() {
	*x = UpdateNewsByIdRequest{}
	mi := &file_news_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNewsByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNewsByIdRequest) ProtoMessage() {}

func (x *UpdateNewsByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNewsByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateNewsByIdRequest) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateNewsByIdRequest) GetCreatorUsername() string {
	if x != nil {
		return x.CreatorUsername
	}
	return ""
}

func (x *UpdateNewsByIdRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNewsByIdRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetOneNewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Excerpt       string                 `protobuf:"bytes,2,opt,name=excerpt,proto3" json:"excerpt,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneNewsResponse) Reset() {
	*x = GetOneNewsResponse{}
	mi := &file_news_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneNewsResponse) ProtoMessage() {}

func (x *GetOneNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneNewsResponse.ProtoReflect.Descriptor instead.
func (*GetOneNewsResponse) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{3}
}

func (x *GetOneNewsResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetOneNewsResponse) GetExcerpt() string {
	if x != nil {
		return x.Excerpt
	}
	return ""
}

func (x *GetOneNewsResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *GetOneNewsResponse) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

type GetAllNewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          []*GetOneNewsResponse  `protobuf:"bytes,1,rep,name=news,proto3" json:"news,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllNewsResponse) Reset() {
	*x = GetAllNewsResponse{}
	mi := &file_news_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllNewsResponse) ProtoMessage() {}

func (x *GetAllNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllNewsResponse.ProtoReflect.Descriptor instead.
func (*GetAllNewsResponse) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllNewsResponse) GetNews() []*GetOneNewsResponse {
	if x != nil {
		return x.News
	}
	return nil
}

type NewsIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsIdResponse) Reset() {
	*x = NewsIdResponse{}
	mi := &file_news_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsIdResponse) ProtoMessage() {}

func (x *NewsIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsIdResponse.ProtoReflect.Descriptor instead.
func (*NewsIdResponse) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{5}
}

func (x *NewsIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_news_proto protoreflect.FileDescriptor

const file_news_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"news.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"0\n" +
	"\x15GetOneNewsByIdRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"\x89\x01\n" +
	"\x11CreateNewsRequest\x122\n" +
	"\x10creator_username\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fcreatorUsername\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\x12!\n" +
	"\acontent\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\acontent\"\x8d\x01\n" +
	"\x15UpdateNewsByIdRequest\x122\n" +
	"\x10creator_username\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fcreatorUsername\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\x12!\n" +
	"\acontent\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\acontent\"\xc4\x01\n" +
	"\x12GetOneNewsResponse\x12\x1d\n" +
	"\x05title\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\x12!\n" +
	"\aexcerpt\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aexcerpt\x12$\n" +
	"\timage_url\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bimageUrl\x12F\n" +
	"\fpublished_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\a\xbaH\x04r\x02\x10\x01R\vpublishedAt\"I\n" +
	"\x12GetAllNewsResponse\x123\n" +
	"\x04news\x18\x01 \x03(\v2\x16.pb.GetOneNewsResponseB\a\xbaH\x04r\x02\x10\x01R\x04news\")\n" +
	"\x0eNewsIdResponse\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02idB-Z+github.com/daniel-bss/havlabs-proto/news/pbb\x06proto3"

var (
	file_news_proto_rawDescOnce sync.Once
	file_news_proto_rawDescData []byte
)

func file_news_proto_rawDescGZIP() []byte {
	file_news_proto_rawDescOnce.Do(func() {
		file_news_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_news_proto_rawDesc), len(file_news_proto_rawDesc)))
	})
	return file_news_proto_rawDescData
}

var file_news_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_news_proto_goTypes = []any{
	(*GetOneNewsByIdRequest)(nil), // 0: pb.GetOneNewsByIdRequest
	(*CreateNewsRequest)(nil),     // 1: pb.CreateNewsRequest
	(*UpdateNewsByIdRequest)(nil), // 2: pb.UpdateNewsByIdRequest
	(*GetOneNewsResponse)(nil),    // 3: pb.GetOneNewsResponse
	(*GetAllNewsResponse)(nil),    // 4: pb.GetAllNewsResponse
	(*NewsIdResponse)(nil),        // 5: pb.NewsIdResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_news_proto_depIdxs = []int32{
	6, // 0: pb.GetOneNewsResponse.published_at:type_name -> google.protobuf.Timestamp
	3, // 1: pb.GetAllNewsResponse.news:type_name -> pb.GetOneNewsResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_news_proto_init() }
func file_news_proto_init() {
	if File_news_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_news_proto_rawDesc), len(file_news_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_news_proto_goTypes,
		DependencyIndexes: file_news_proto_depIdxs,
		MessageInfos:      file_news_proto_msgTypes,
	}.Build()
	File_news_proto = out.File
	file_news_proto_goTypes = nil
	file_news_proto_depIdxs = nil
}
