// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: service_auth.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_auth_proto protoreflect.FileDescriptor

const file_service_auth_proto_rawDesc = "" +
	"\n" +
	"\x12service_auth.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15rpc_create_user.proto\x1a\x15rpc_update_user.proto\x1a\x0frpc_login.proto\x1a\x11renew_token.proto\x1a\n" +
	"jwks.proto2\xa3\x03\n" +
	"\vHavlabsAuth\x12?\n" +
	"\x05Login\x12\x10.pb.LoginRequest\x1a\x11.pb.LoginResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/login\x12Q\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/register\x12U\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/users/update\x12S\n" +
	"\aGetJWKS\x12\x16.google.protobuf.Empty\x1a\x10.pb.JWKSResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/.well-known/jwks.json\x12T\n" +
	"\n" +
	"RenewToken\x12\x15.pb.RenewTokenRequest\x1a\x16.pb.RenewTokenResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/renew-tokenB-Z+github.com/daniel-bss/havlabs-proto/auth/pbb\x06proto3"

var file_service_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),       // 0: pb.LoginRequest
	(*CreateUserRequest)(nil),  // 1: pb.CreateUserRequest
	(*UpdateUserRequest)(nil),  // 2: pb.UpdateUserRequest
	(*emptypb.Empty)(nil),      // 3: google.protobuf.Empty
	(*RenewTokenRequest)(nil),  // 4: pb.RenewTokenRequest
	(*LoginResponse)(nil),      // 5: pb.LoginResponse
	(*CreateUserResponse)(nil), // 6: pb.CreateUserResponse
	(*UpdateUserResponse)(nil), // 7: pb.UpdateUserResponse
	(*JWKSResponse)(nil),       // 8: pb.JWKSResponse
	(*RenewTokenResponse)(nil), // 9: pb.RenewTokenResponse
}
var file_service_auth_proto_depIdxs = []int32{
	0, // 0: pb.HavlabsAuth.Login:input_type -> pb.LoginRequest
	1, // 1: pb.HavlabsAuth.CreateUser:input_type -> pb.CreateUserRequest
	2, // 2: pb.HavlabsAuth.UpdateUser:input_type -> pb.UpdateUserRequest
	3, // 3: pb.HavlabsAuth.GetJWKS:input_type -> google.protobuf.Empty
	4, // 4: pb.HavlabsAuth.RenewToken:input_type -> pb.RenewTokenRequest
	5, // 5: pb.HavlabsAuth.Login:output_type -> pb.LoginResponse
	6, // 6: pb.HavlabsAuth.CreateUser:output_type -> pb.CreateUserResponse
	7, // 7: pb.HavlabsAuth.UpdateUser:output_type -> pb.UpdateUserResponse
	8, // 8: pb.HavlabsAuth.GetJWKS:output_type -> pb.JWKSResponse
	9, // 9: pb.HavlabsAuth.RenewToken:output_type -> pb.RenewTokenResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_auth_proto_init() }
func file_service_auth_proto_init() {
	if File_service_auth_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_login_proto_init()
	file_renew_token_proto_init()
	file_jwks_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_auth_proto_rawDesc), len(file_service_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_auth_proto_goTypes,
		DependencyIndexes: file_service_auth_proto_depIdxs,
	}.Build()
	File_service_auth_proto = out.File
	file_service_auth_proto_goTypes = nil
	file_service_auth_proto_depIdxs = nil
}
