// service-one.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: service-one.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceOne_Hello_FullMethodName = "/pb.ServiceOne/Hello"
)

// ServiceOneClient is the client API for ServiceOne service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceOneClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type serviceOneClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceOneClient(cc grpc.ClientConnInterface) ServiceOneClient {
	return &serviceOneClient{cc}
}

func (c *serviceOneClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, ServiceOne_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceOneServer is the server API for ServiceOne service.
// All implementations must embed UnimplementedServiceOneServer
// for forward compatibility.
type ServiceOneServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedServiceOneServer()
}

// UnimplementedServiceOneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceOneServer struct{}

func (UnimplementedServiceOneServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedServiceOneServer) mustEmbedUnimplementedServiceOneServer() {}
func (UnimplementedServiceOneServer) testEmbeddedByValue()                    {}

// UnsafeServiceOneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceOneServer will
// result in compilation errors.
type UnsafeServiceOneServer interface {
	mustEmbedUnimplementedServiceOneServer()
}

func RegisterServiceOneServer(s grpc.ServiceRegistrar, srv ServiceOneServer) {
	// If the following call panics, it indicates UnimplementedServiceOneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceOne_ServiceDesc, srv)
}

func _ServiceOne_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceOneServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceOne_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceOneServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceOne_ServiceDesc is the grpc.ServiceDesc for ServiceOne service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceOne_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ServiceOne",
	HandlerType: (*ServiceOneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _ServiceOne_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service-one.proto",
}
