// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: service_media.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HavlabsMedia_CreateUploadSession_FullMethodName = "/pb.HavlabsMedia/CreateUploadSession"
	HavlabsMedia_ConfirmUpload_FullMethodName       = "/pb.HavlabsMedia/ConfirmUpload"
	HavlabsMedia_GetMediaById_FullMethodName        = "/pb.HavlabsMedia/GetMediaById"
)

// HavlabsMediaClient is the client API for HavlabsMedia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HavlabsMediaClient interface {
	CreateUploadSession(ctx context.Context, in *CreateUploadSessionRequest, opts ...grpc.CallOption) (*CreateUploadSessionResponse, error)
	ConfirmUpload(ctx context.Context, in *ConfirmUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error)
	GetMediaById(ctx context.Context, in *GetOneMediaByIdRequest, opts ...grpc.CallOption) (*OneMediaResponse, error)
}

type havlabsMediaClient struct {
	cc grpc.ClientConnInterface
}

func NewHavlabsMediaClient(cc grpc.ClientConnInterface) HavlabsMediaClient {
	return &havlabsMediaClient{cc}
}

func (c *havlabsMediaClient) CreateUploadSession(ctx context.Context, in *CreateUploadSessionRequest, opts ...grpc.CallOption) (*CreateUploadSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUploadSessionResponse)
	err := c.cc.Invoke(ctx, HavlabsMedia_CreateUploadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *havlabsMediaClient) ConfirmUpload(ctx context.Context, in *ConfirmUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmUploadResponse)
	err := c.cc.Invoke(ctx, HavlabsMedia_ConfirmUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *havlabsMediaClient) GetMediaById(ctx context.Context, in *GetOneMediaByIdRequest, opts ...grpc.CallOption) (*OneMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OneMediaResponse)
	err := c.cc.Invoke(ctx, HavlabsMedia_GetMediaById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HavlabsMediaServer is the server API for HavlabsMedia service.
// All implementations must embed UnimplementedHavlabsMediaServer
// for forward compatibility.
type HavlabsMediaServer interface {
	CreateUploadSession(context.Context, *CreateUploadSessionRequest) (*CreateUploadSessionResponse, error)
	ConfirmUpload(context.Context, *ConfirmUploadRequest) (*ConfirmUploadResponse, error)
	GetMediaById(context.Context, *GetOneMediaByIdRequest) (*OneMediaResponse, error)
	mustEmbedUnimplementedHavlabsMediaServer()
}

// UnimplementedHavlabsMediaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHavlabsMediaServer struct{}

func (UnimplementedHavlabsMediaServer) CreateUploadSession(context.Context, *CreateUploadSessionRequest) (*CreateUploadSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUploadSession not implemented")
}
func (UnimplementedHavlabsMediaServer) ConfirmUpload(context.Context, *ConfirmUploadRequest) (*ConfirmUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmUpload not implemented")
}
func (UnimplementedHavlabsMediaServer) GetMediaById(context.Context, *GetOneMediaByIdRequest) (*OneMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMediaById not implemented")
}
func (UnimplementedHavlabsMediaServer) mustEmbedUnimplementedHavlabsMediaServer() {}
func (UnimplementedHavlabsMediaServer) testEmbeddedByValue()                      {}

// UnsafeHavlabsMediaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HavlabsMediaServer will
// result in compilation errors.
type UnsafeHavlabsMediaServer interface {
	mustEmbedUnimplementedHavlabsMediaServer()
}

func RegisterHavlabsMediaServer(s grpc.ServiceRegistrar, srv HavlabsMediaServer) {
	// If the following call panics, it indicates UnimplementedHavlabsMediaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HavlabsMedia_ServiceDesc, srv)
}

func _HavlabsMedia_CreateUploadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsMediaServer).CreateUploadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsMedia_CreateUploadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsMediaServer).CreateUploadSession(ctx, req.(*CreateUploadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HavlabsMedia_ConfirmUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsMediaServer).ConfirmUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsMedia_ConfirmUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsMediaServer).ConfirmUpload(ctx, req.(*ConfirmUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HavlabsMedia_GetMediaById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneMediaByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsMediaServer).GetMediaById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsMedia_GetMediaById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsMediaServer).GetMediaById(ctx, req.(*GetOneMediaByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HavlabsMedia_ServiceDesc is the grpc.ServiceDesc for HavlabsMedia service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HavlabsMedia_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HavlabsMedia",
	HandlerType: (*HavlabsMediaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUploadSession",
			Handler:    _HavlabsMedia_CreateUploadSession_Handler,
		},
		{
			MethodName: "ConfirmUpload",
			Handler:    _HavlabsMedia_ConfirmUpload_Handler,
		},
		{
			MethodName: "GetMediaById",
			Handler:    _HavlabsMedia_GetMediaById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_media.proto",
}
