// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: service_news.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HavlabsNews_GetPaginatedNews_FullMethodName = "/pb.HavlabsNews/GetPaginatedNews"
	HavlabsNews_GetOneNews_FullMethodName       = "/pb.HavlabsNews/GetOneNews"
	HavlabsNews_CreateNews_FullMethodName       = "/pb.HavlabsNews/CreateNews"
	HavlabsNews_UpdateNews_FullMethodName       = "/pb.HavlabsNews/UpdateNews"
	HavlabsNews_DeleteNews_FullMethodName       = "/pb.HavlabsNews/DeleteNews"
)

// HavlabsNewsClient is the client API for HavlabsNews service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HavlabsNewsClient interface {
	GetPaginatedNews(ctx context.Context, in *ListNewsRequest, opts ...grpc.CallOption) (*ListNewsResponse, error)
	GetOneNews(ctx context.Context, in *GetOneNewsByIdRequest, opts ...grpc.CallOption) (*OneNewsResponse, error)
	CreateNews(ctx context.Context, in *CreateNewsRequest, opts ...grpc.CallOption) (*NewsIdResponse, error)
	UpdateNews(ctx context.Context, in *UpdateNewsByIdRequest, opts ...grpc.CallOption) (*NewsIdResponse, error)
	DeleteNews(ctx context.Context, in *GetOneNewsByIdRequest, opts ...grpc.CallOption) (*NewsIdResponse, error)
}

type havlabsNewsClient struct {
	cc grpc.ClientConnInterface
}

func NewHavlabsNewsClient(cc grpc.ClientConnInterface) HavlabsNewsClient {
	return &havlabsNewsClient{cc}
}

func (c *havlabsNewsClient) GetPaginatedNews(ctx context.Context, in *ListNewsRequest, opts ...grpc.CallOption) (*ListNewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNewsResponse)
	err := c.cc.Invoke(ctx, HavlabsNews_GetPaginatedNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *havlabsNewsClient) GetOneNews(ctx context.Context, in *GetOneNewsByIdRequest, opts ...grpc.CallOption) (*OneNewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OneNewsResponse)
	err := c.cc.Invoke(ctx, HavlabsNews_GetOneNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *havlabsNewsClient) CreateNews(ctx context.Context, in *CreateNewsRequest, opts ...grpc.CallOption) (*NewsIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewsIdResponse)
	err := c.cc.Invoke(ctx, HavlabsNews_CreateNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *havlabsNewsClient) UpdateNews(ctx context.Context, in *UpdateNewsByIdRequest, opts ...grpc.CallOption) (*NewsIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewsIdResponse)
	err := c.cc.Invoke(ctx, HavlabsNews_UpdateNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *havlabsNewsClient) DeleteNews(ctx context.Context, in *GetOneNewsByIdRequest, opts ...grpc.CallOption) (*NewsIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewsIdResponse)
	err := c.cc.Invoke(ctx, HavlabsNews_DeleteNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HavlabsNewsServer is the server API for HavlabsNews service.
// All implementations must embed UnimplementedHavlabsNewsServer
// for forward compatibility.
type HavlabsNewsServer interface {
	GetPaginatedNews(context.Context, *ListNewsRequest) (*ListNewsResponse, error)
	GetOneNews(context.Context, *GetOneNewsByIdRequest) (*OneNewsResponse, error)
	CreateNews(context.Context, *CreateNewsRequest) (*NewsIdResponse, error)
	UpdateNews(context.Context, *UpdateNewsByIdRequest) (*NewsIdResponse, error)
	DeleteNews(context.Context, *GetOneNewsByIdRequest) (*NewsIdResponse, error)
	mustEmbedUnimplementedHavlabsNewsServer()
}

// UnimplementedHavlabsNewsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHavlabsNewsServer struct{}

func (UnimplementedHavlabsNewsServer) GetPaginatedNews(context.Context, *ListNewsRequest) (*ListNewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaginatedNews not implemented")
}
func (UnimplementedHavlabsNewsServer) GetOneNews(context.Context, *GetOneNewsByIdRequest) (*OneNewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOneNews not implemented")
}
func (UnimplementedHavlabsNewsServer) CreateNews(context.Context, *CreateNewsRequest) (*NewsIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNews not implemented")
}
func (UnimplementedHavlabsNewsServer) UpdateNews(context.Context, *UpdateNewsByIdRequest) (*NewsIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNews not implemented")
}
func (UnimplementedHavlabsNewsServer) DeleteNews(context.Context, *GetOneNewsByIdRequest) (*NewsIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNews not implemented")
}
func (UnimplementedHavlabsNewsServer) mustEmbedUnimplementedHavlabsNewsServer() {}
func (UnimplementedHavlabsNewsServer) testEmbeddedByValue()                     {}

// UnsafeHavlabsNewsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HavlabsNewsServer will
// result in compilation errors.
type UnsafeHavlabsNewsServer interface {
	mustEmbedUnimplementedHavlabsNewsServer()
}

func RegisterHavlabsNewsServer(s grpc.ServiceRegistrar, srv HavlabsNewsServer) {
	// If the following call panics, it indicates UnimplementedHavlabsNewsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HavlabsNews_ServiceDesc, srv)
}

func _HavlabsNews_GetPaginatedNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsNewsServer).GetPaginatedNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsNews_GetPaginatedNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsNewsServer).GetPaginatedNews(ctx, req.(*ListNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HavlabsNews_GetOneNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneNewsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsNewsServer).GetOneNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsNews_GetOneNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsNewsServer).GetOneNews(ctx, req.(*GetOneNewsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HavlabsNews_CreateNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsNewsServer).CreateNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsNews_CreateNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsNewsServer).CreateNews(ctx, req.(*CreateNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HavlabsNews_UpdateNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNewsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsNewsServer).UpdateNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsNews_UpdateNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsNewsServer).UpdateNews(ctx, req.(*UpdateNewsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HavlabsNews_DeleteNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneNewsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsNewsServer).DeleteNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsNews_DeleteNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsNewsServer).DeleteNews(ctx, req.(*GetOneNewsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HavlabsNews_ServiceDesc is the grpc.ServiceDesc for HavlabsNews service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HavlabsNews_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HavlabsNews",
	HandlerType: (*HavlabsNewsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPaginatedNews",
			Handler:    _HavlabsNews_GetPaginatedNews_Handler,
		},
		{
			MethodName: "GetOneNews",
			Handler:    _HavlabsNews_GetOneNews_Handler,
		},
		{
			MethodName: "CreateNews",
			Handler:    _HavlabsNews_CreateNews_Handler,
		},
		{
			MethodName: "UpdateNews",
			Handler:    _HavlabsNews_UpdateNews_Handler,
		},
		{
			MethodName: "DeleteNews",
			Handler:    _HavlabsNews_DeleteNews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_news.proto",
}
