// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: service_media.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SomeResponse) Reset() {
	*x = SomeResponse{}
	mi := &file_service_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomeResponse) ProtoMessage() {}

func (x *SomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SomeResponse.ProtoReflect.Descriptor instead.
func (*SomeResponse) Descriptor() ([]byte, []int) {
	return file_service_media_proto_rawDescGZIP(), []int{0}
}

func (x *SomeResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_service_media_proto protoreflect.FileDescriptor

const file_service_media_proto_rawDesc = "" +
	"\n" +
	"\x13service_media.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\" \n" +
	"\fSomeResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2[\n" +
	"\fHavlabsMedia\x12K\n" +
	"\x0fCreateUploadURL\x12\x16.google.protobuf.Empty\x1a\x10.pb.SomeResponse\"\x0e\x82\xd3\xe4\x93\x02\b\"\x06/mediaB.Z,github.com/daniel-bss/havlabs-proto/media/pbb\x06proto3"

var (
	file_service_media_proto_rawDescOnce sync.Once
	file_service_media_proto_rawDescData []byte
)

func file_service_media_proto_rawDescGZIP() []byte {
	file_service_media_proto_rawDescOnce.Do(func() {
		file_service_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_media_proto_rawDesc), len(file_service_media_proto_rawDesc)))
	})
	return file_service_media_proto_rawDescData
}

var file_service_media_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_service_media_proto_goTypes = []any{
	(*SomeResponse)(nil),  // 0: pb.SomeResponse
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_service_media_proto_depIdxs = []int32{
	1, // 0: pb.HavlabsMedia.CreateUploadURL:input_type -> google.protobuf.Empty
	0, // 1: pb.HavlabsMedia.CreateUploadURL:output_type -> pb.SomeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_media_proto_init() }
func file_service_media_proto_init() {
	if File_service_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_media_proto_rawDesc), len(file_service_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_media_proto_goTypes,
		DependencyIndexes: file_service_media_proto_depIdxs,
		MessageInfos:      file_service_media_proto_msgTypes,
	}.Build()
	File_service_media_proto = out.File
	file_service_media_proto_goTypes = nil
	file_service_media_proto_depIdxs = nil
}
