// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: service_media.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_media_proto protoreflect.FileDescriptor

const file_service_media_proto_rawDesc = "" +
	"\n" +
	"\x13service_media.proto\x12\x02pb\x1a\vmedia.proto\x1a\x1cgoogle/api/annotations.proto2\xa1\x03\n" +
	"\fHavlabsMedia\x12x\n" +
	"\x13CreateUploadSession\x12\x1e.pb.CreateUploadSessionRequest\x1a\x1f.pb.CreateUploadSessionResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/media/upload-session\x12c\n" +
	"\rConfirmUpload\x12\x18.pb.ConfirmUploadRequest\x1a\x19.pb.ConfirmUploadResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x15/media/confirm-upload\x12U\n" +
	"\fGetMediaById\x12\x1a.pb.GetOneMediaByIdRequest\x1a\x14.pb.OneMediaResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/media/{id}\x12[\n" +
	"\vGetMediaURL\x12\x1a.pb.GetOneMediaByIdRequest\x1a\x17.pb.OneMediaURLResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/media/{id}/urlB.Z,github.com/daniel-bss/havlabs-proto/media/pbb\x06proto3"

var file_service_media_proto_goTypes = []any{
	(*CreateUploadSessionRequest)(nil),  // 0: pb.CreateUploadSessionRequest
	(*ConfirmUploadRequest)(nil),        // 1: pb.ConfirmUploadRequest
	(*GetOneMediaByIdRequest)(nil),      // 2: pb.GetOneMediaByIdRequest
	(*CreateUploadSessionResponse)(nil), // 3: pb.CreateUploadSessionResponse
	(*ConfirmUploadResponse)(nil),       // 4: pb.ConfirmUploadResponse
	(*OneMediaResponse)(nil),            // 5: pb.OneMediaResponse
	(*OneMediaURLResponse)(nil),         // 6: pb.OneMediaURLResponse
}
var file_service_media_proto_depIdxs = []int32{
	0, // 0: pb.HavlabsMedia.CreateUploadSession:input_type -> pb.CreateUploadSessionRequest
	1, // 1: pb.HavlabsMedia.ConfirmUpload:input_type -> pb.ConfirmUploadRequest
	2, // 2: pb.HavlabsMedia.GetMediaById:input_type -> pb.GetOneMediaByIdRequest
	2, // 3: pb.HavlabsMedia.GetMediaURL:input_type -> pb.GetOneMediaByIdRequest
	3, // 4: pb.HavlabsMedia.CreateUploadSession:output_type -> pb.CreateUploadSessionResponse
	4, // 5: pb.HavlabsMedia.ConfirmUpload:output_type -> pb.ConfirmUploadResponse
	5, // 6: pb.HavlabsMedia.GetMediaById:output_type -> pb.OneMediaResponse
	6, // 7: pb.HavlabsMedia.GetMediaURL:output_type -> pb.OneMediaURLResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_media_proto_init() }
func file_service_media_proto_init() {
	if File_service_media_proto != nil {
		return
	}
	file_media_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_media_proto_rawDesc), len(file_service_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_media_proto_goTypes,
		DependencyIndexes: file_service_media_proto_depIdxs,
	}.Build()
	File_service_media_proto = out.File
	file_service_media_proto_goTypes = nil
	file_service_media_proto_depIdxs = nil
}
