// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: service_auth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HavlabsAuth_Login_FullMethodName      = "/pb.HavlabsAuth/Login"
	HavlabsAuth_CreateUser_FullMethodName = "/pb.HavlabsAuth/CreateUser"
	HavlabsAuth_UpdateUser_FullMethodName = "/pb.HavlabsAuth/UpdateUser"
	HavlabsAuth_GetJWKS_FullMethodName    = "/pb.HavlabsAuth/GetJWKS"
	HavlabsAuth_RenewToken_FullMethodName = "/pb.HavlabsAuth/RenewToken"
)

// HavlabsAuthClient is the client API for HavlabsAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HavlabsAuthClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	GetJWKS(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JWKSResponse, error)
	RenewToken(ctx context.Context, in *RenewTokenRequest, opts ...grpc.CallOption) (*JWKSResponse, error)
}

type havlabsAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewHavlabsAuthClient(cc grpc.ClientConnInterface) HavlabsAuthClient {
	return &havlabsAuthClient{cc}
}

func (c *havlabsAuthClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, HavlabsAuth_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *havlabsAuthClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, HavlabsAuth_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *havlabsAuthClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, HavlabsAuth_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *havlabsAuthClient) GetJWKS(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JWKSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JWKSResponse)
	err := c.cc.Invoke(ctx, HavlabsAuth_GetJWKS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *havlabsAuthClient) RenewToken(ctx context.Context, in *RenewTokenRequest, opts ...grpc.CallOption) (*JWKSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JWKSResponse)
	err := c.cc.Invoke(ctx, HavlabsAuth_RenewToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HavlabsAuthServer is the server API for HavlabsAuth service.
// All implementations must embed UnimplementedHavlabsAuthServer
// for forward compatibility.
type HavlabsAuthServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	GetJWKS(context.Context, *emptypb.Empty) (*JWKSResponse, error)
	RenewToken(context.Context, *RenewTokenRequest) (*JWKSResponse, error)
	mustEmbedUnimplementedHavlabsAuthServer()
}

// UnimplementedHavlabsAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHavlabsAuthServer struct{}

func (UnimplementedHavlabsAuthServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedHavlabsAuthServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedHavlabsAuthServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedHavlabsAuthServer) GetJWKS(context.Context, *emptypb.Empty) (*JWKSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJWKS not implemented")
}
func (UnimplementedHavlabsAuthServer) RenewToken(context.Context, *RenewTokenRequest) (*JWKSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewToken not implemented")
}
func (UnimplementedHavlabsAuthServer) mustEmbedUnimplementedHavlabsAuthServer() {}
func (UnimplementedHavlabsAuthServer) testEmbeddedByValue()                     {}

// UnsafeHavlabsAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HavlabsAuthServer will
// result in compilation errors.
type UnsafeHavlabsAuthServer interface {
	mustEmbedUnimplementedHavlabsAuthServer()
}

func RegisterHavlabsAuthServer(s grpc.ServiceRegistrar, srv HavlabsAuthServer) {
	// If the following call panics, it indicates UnimplementedHavlabsAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HavlabsAuth_ServiceDesc, srv)
}

func _HavlabsAuth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsAuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsAuth_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsAuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HavlabsAuth_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsAuthServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsAuth_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsAuthServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HavlabsAuth_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsAuthServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsAuth_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsAuthServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HavlabsAuth_GetJWKS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsAuthServer).GetJWKS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsAuth_GetJWKS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsAuthServer).GetJWKS(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HavlabsAuth_RenewToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsAuthServer).RenewToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsAuth_RenewToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsAuthServer).RenewToken(ctx, req.(*RenewTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HavlabsAuth_ServiceDesc is the grpc.ServiceDesc for HavlabsAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HavlabsAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HavlabsAuth",
	HandlerType: (*HavlabsAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _HavlabsAuth_Login_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _HavlabsAuth_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _HavlabsAuth_UpdateUser_Handler,
		},
		{
			MethodName: "GetJWKS",
			Handler:    _HavlabsAuth_GetJWKS_Handler,
		},
		{
			MethodName: "RenewToken",
			Handler:    _HavlabsAuth_RenewToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_auth.proto",
}
