// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: service_news.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_news_proto protoreflect.FileDescriptor

const file_service_news_proto_rawDesc = "" +
	"\n" +
	"\x12service_news.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\n" +
	"news.proto2N\n" +
	"\vHavlabsNews\x12?\n" +
	"\aGetNews\x12\x0f.pb.NewsRequest\x1a\x10.pb.NewsResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/loginB0Z.github.com/daniel-bss/havlabs/internal/news/pbb\x06proto3"

var file_service_news_proto_goTypes = []any{
	(*NewsRequest)(nil),  // 0: pb.NewsRequest
	(*NewsResponse)(nil), // 1: pb.NewsResponse
}
var file_service_news_proto_depIdxs = []int32{
	0, // 0: pb.HavlabsNews.GetNews:input_type -> pb.NewsRequest
	1, // 1: pb.HavlabsNews.GetNews:output_type -> pb.NewsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_news_proto_init() }
func file_service_news_proto_init() {
	if File_service_news_proto != nil {
		return
	}
	file_news_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_news_proto_rawDesc), len(file_service_news_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_news_proto_goTypes,
		DependencyIndexes: file_service_news_proto_depIdxs,
	}.Build()
	File_service_news_proto = out.File
	file_service_news_proto_goTypes = nil
	file_service_news_proto_depIdxs = nil
}
