// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: service_news.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HavlabsNews_GetNews_FullMethodName = "/pb.HavlabsNews/GetNews"
)

// HavlabsNewsClient is the client API for HavlabsNews service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HavlabsNewsClient interface {
	GetNews(ctx context.Context, in *NewsRequest, opts ...grpc.CallOption) (*NewsResponse, error)
}

type havlabsNewsClient struct {
	cc grpc.ClientConnInterface
}

func NewHavlabsNewsClient(cc grpc.ClientConnInterface) HavlabsNewsClient {
	return &havlabsNewsClient{cc}
}

func (c *havlabsNewsClient) GetNews(ctx context.Context, in *NewsRequest, opts ...grpc.CallOption) (*NewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewsResponse)
	err := c.cc.Invoke(ctx, HavlabsNews_GetNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HavlabsNewsServer is the server API for HavlabsNews service.
// All implementations must embed UnimplementedHavlabsNewsServer
// for forward compatibility.
type HavlabsNewsServer interface {
	GetNews(context.Context, *NewsRequest) (*NewsResponse, error)
	mustEmbedUnimplementedHavlabsNewsServer()
}

// UnimplementedHavlabsNewsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHavlabsNewsServer struct{}

func (UnimplementedHavlabsNewsServer) GetNews(context.Context, *NewsRequest) (*NewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNews not implemented")
}
func (UnimplementedHavlabsNewsServer) mustEmbedUnimplementedHavlabsNewsServer() {}
func (UnimplementedHavlabsNewsServer) testEmbeddedByValue()                     {}

// UnsafeHavlabsNewsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HavlabsNewsServer will
// result in compilation errors.
type UnsafeHavlabsNewsServer interface {
	mustEmbedUnimplementedHavlabsNewsServer()
}

func RegisterHavlabsNewsServer(s grpc.ServiceRegistrar, srv HavlabsNewsServer) {
	// If the following call panics, it indicates UnimplementedHavlabsNewsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HavlabsNews_ServiceDesc, srv)
}

func _HavlabsNews_GetNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HavlabsNewsServer).GetNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HavlabsNews_GetNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HavlabsNewsServer).GetNews(ctx, req.(*NewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HavlabsNews_ServiceDesc is the grpc.ServiceDesc for HavlabsNews service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HavlabsNews_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HavlabsNews",
	HandlerType: (*HavlabsNewsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNews",
			Handler:    _HavlabsNews_GetNews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_news.proto",
}
