// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: service_news.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_news_proto protoreflect.FileDescriptor

const file_service_news_proto_rawDesc = "" +
	"\n" +
	"\x12service_news.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\n" +
	"news.proto2\x99\x03\n" +
	"\vHavlabsNews\x12L\n" +
	"\x10GetPaginatedNews\x12\x13.pb.ListNewsRequest\x1a\x14.pb.ListNewsResponse\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/news\x12S\n" +
	"\n" +
	"GetOneNews\x12\x19.pb.GetOneNewsByIdRequest\x1a\x13.pb.OneNewsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\x12\n" +
	"/news/{id}\x12I\n" +
	"\n" +
	"CreateNews\x12\x15.pb.CreateNewsRequest\x1a\x12.pb.NewsIdResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/news\x12M\n" +
	"\n" +
	"UpdateNews\x12\x19.pb.UpdateNewsByIdRequest\x1a\x12.pb.NewsIdResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\x1a\x05/news\x12M\n" +
	"\n" +
	"DeleteNews\x12\x19.pb.GetOneNewsByIdRequest\x1a\x12.pb.NewsIdResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01**\x05/newsB-Z+github.com/daniel-bss/havlabs-proto/news/pbb\x06proto3"

var file_service_news_proto_goTypes = []any{
	(*ListNewsRequest)(nil),       // 0: pb.ListNewsRequest
	(*GetOneNewsByIdRequest)(nil), // 1: pb.GetOneNewsByIdRequest
	(*CreateNewsRequest)(nil),     // 2: pb.CreateNewsRequest
	(*UpdateNewsByIdRequest)(nil), // 3: pb.UpdateNewsByIdRequest
	(*ListNewsResponse)(nil),      // 4: pb.ListNewsResponse
	(*OneNewsResponse)(nil),       // 5: pb.OneNewsResponse
	(*NewsIdResponse)(nil),        // 6: pb.NewsIdResponse
}
var file_service_news_proto_depIdxs = []int32{
	0, // 0: pb.HavlabsNews.GetPaginatedNews:input_type -> pb.ListNewsRequest
	1, // 1: pb.HavlabsNews.GetOneNews:input_type -> pb.GetOneNewsByIdRequest
	2, // 2: pb.HavlabsNews.CreateNews:input_type -> pb.CreateNewsRequest
	3, // 3: pb.HavlabsNews.UpdateNews:input_type -> pb.UpdateNewsByIdRequest
	1, // 4: pb.HavlabsNews.DeleteNews:input_type -> pb.GetOneNewsByIdRequest
	4, // 5: pb.HavlabsNews.GetPaginatedNews:output_type -> pb.ListNewsResponse
	5, // 6: pb.HavlabsNews.GetOneNews:output_type -> pb.OneNewsResponse
	6, // 7: pb.HavlabsNews.CreateNews:output_type -> pb.NewsIdResponse
	6, // 8: pb.HavlabsNews.UpdateNews:output_type -> pb.NewsIdResponse
	6, // 9: pb.HavlabsNews.DeleteNews:output_type -> pb.NewsIdResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_news_proto_init() }
func file_service_news_proto_init() {
	if File_service_news_proto != nil {
		return
	}
	file_news_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_news_proto_rawDesc), len(file_service_news_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_news_proto_goTypes,
		DependencyIndexes: file_service_news_proto_depIdxs,
	}.Build()
	File_service_news_proto = out.File
	file_service_news_proto_goTypes = nil
	file_service_news_proto_depIdxs = nil
}
